// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Tg9IxJO_FeuXhy3fmjk4tqJns0H-rEM',
    appId: '1:850287076834:web:71fa7fd05164f6002ac5bb',
    messagingSenderId: '850287076834',
    projectId: 'show-list-7675',
    authDomain: 'show-list-7675.firebaseapp.com',
    storageBucket: 'show-list-7675.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFhX671DCgz-u8tzQgduWfvb50S0TenBA',
    appId: '1:850287076834:android:9279df0bbc6dc2b52ac5bb',
    messagingSenderId: '850287076834',
    projectId: 'show-list-7675',
    storageBucket: 'show-list-7675.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy_jOwLOsgAVraZc-lwh7JFjRicghzgaA',
    appId: '1:850287076834:ios:359136a5a4b54c712ac5bb',
    messagingSenderId: '850287076834',
    projectId: 'show-list-7675',
    storageBucket: 'show-list-7675.appspot.com',
    iosClientId: '850287076834-4civi76tbp33g5ar0qrm4c229tmk4n4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.showList',
  );
}
